version: '3.3'
services:
  web:
    image: jeeni/docker-test:hbaf1
    ports:
      - "8080:8080"
    container_name: springboot
    restart: always
    depends_on:
      - mysql-db
      - redis-db
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    env_file:
      - ./mysql.env
    restart: always
  redis-db:
    image: redis:latest
    container_name: redis-db
    hostname: redis
    ports:
      - "6379:6379"